version: '3.7'

services: 
  blogapi:
    image: blogapi
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 8001:8000
    links:
      - db
    environment:
      - DB_HOST=${DATABASE_HOSTNAME}
      - DB_PORT=${DATABASE_PORT}
      - DB_USER=${DATABASE_USERNAME}
      - DB_PASSWORD=${DATABASE_PASSWORD}
      - DB_NAME=${DATABASE_NAME}
    networks:
      - app-network
  db:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: blogapi12345678
      MYSQL_DATABASE: ${DATABASE_NAME}
      MYSQL_USER: ${DATABASE_USERNAME}
      MYSQL_PASSWORD: ${DATABASE_PASSWORD}
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - app-network
networks:
  app-network:
    driver: bridge
volumes:
    db_data:
        driver: local
  